{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-app.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "todo-app.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.global.imageRegistry }}{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        env:
        - name: NEXT_PUBLIC_USER_SERVICE_URL
          value: {{ .Values.frontend.env.userServiceUrl | default (printf "http://user-service:%d" (.Values.userService.service.port | int)) | quote }}
        - name: NEXT_PUBLIC_TODO_SERVICE_URL
          value: {{ .Values.frontend.env.todoServiceUrl | default (printf "http://todo-service:%d" (.Values.todoService.service.port | int)) | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    component: frontend
spec:
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    component: frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    protocol: TCP
  type: {{ .Values.frontend.service.type }}
{{- end }}
