{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: todo-app-gateway
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: todo-app-routes
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: todo-app-gateway
  rules:
  # Frontend route
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend
      port: {{ .Values.frontend.service.port }}
  # User service API routes
  - matches:
    - path:
        type: PathPrefix
        value: /api/users
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: user-service
      port: {{ .Values.userService.service.port }}
  # Todo service API routes
  - matches:
    - path:
        type: PathPrefix
        value: /api/todos
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: todo-service
      port: {{ .Values.todoService.service.port }}
{{- end }}
