{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app: {{ include "todo-app.name" . }}
    environment: {{ .Values.global.environment }}
{{- end }}
