apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
