apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-staging
  namespace: argocd
  labels:
    app: todo-app
    environment: staging
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: HEAD
    path: helm/todo-app
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: global.imageRegistry
          value: ${ECR_REGISTRY}
        - name: userService.image.tag
          value: ${IMAGE_TAG}
        - name: todoService.image.tag
          value: ${IMAGE_TAG}
        - name: frontend.image.tag
          value: ${IMAGE_TAG}
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-prod
  namespace: argocd
  labels:
    app: todo-app
    environment: prod
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: HEAD
    path: helm/todo-app
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: global.imageRegistry
          value: ${ECR_REGISTRY}
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
