apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml

# Replace variables with actual values during deployment
replacements:
  - source:
      kind: ConfigMap
      name: argocd-config
      fieldPath: data.REPO_URL
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.repoURL
  - source:
      kind: ConfigMap
      name: argocd-config
      fieldPath: data.ECR_REGISTRY
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.helm.parameters.[name=global.imageRegistry].value
  - source:
      kind: ConfigMap
      name: argocd-config
      fieldPath: data.IMAGE_TAG
    targets:
      - select:
          kind: Application
          name: todo-app-staging
        fieldPaths:
          - spec.source.helm.parameters.[name=userService.image.tag].value
          - spec.source.helm.parameters.[name=todoService.image.tag].value
          - spec.source.helm.parameters.[name=frontend.image.tag].value

generatorOptions:
  disableNameSuffixHash: true
