apiVersion: v2
name: todo-app
description: A microservices-based todo application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - todo
  - microservices
  - fastapi
  - nextjs
home: https://github.com/your-username/todo-app
sources:
  - https://github.com/your-username/todo-app
maintainers:
  - name: DevOps Engineer
    email: devops@company.com
